language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"
  # PyPy versions
  - "pypy3.5"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script: py.test --cov=./ ; codecov
